name: Build and deploy Python project to Azure Function App - geometry-func-nur

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9AAA2D0106204958A58FBBD2E440E43D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7D8CCAE41BF347FC857189894F739135 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2D49AFA71BA54B63968BAC2774DCD2C9 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'geometry-func-nur'
          slot-name: 'Production'
          package: './api'
          scm-do-build-during-deployment: true